### ISSUE TITLE
Rails 5

### ISSUE THREAD

**Issue by esambo** [lowjoel/simple_form-bootstrap#6]
How about Rails 5 compatibility?
https://github.com/lowjoel/simple_form-bootstrap/blob/master/simple_form-bootstrap.gemspec#L26-L28

**Comment by lowjoel** [comment]
I haven't tested it. If you've tried it and it works, feel free to raise a PR to change it to `>= 4.0`, `< 6`

**Comment by esambo** [comment]
I have never used this gem before and was just looking around.
